### ISSUE TITLE
Desired behavior without modifying the JSlib

### ISSUE THREAD

**Issue by ethan-evans-gd** [rwinright/Unity-WebSockets-Test#1]
#

https://github.com/rwinright/Unity-WebSockets-Test/blob/4bb54596bad7ce555e67f7c97213efe8ffcca004/UnityProject/webgl-client-project/Assets/Plugins/WebSocket.jslib#L190

The above line evaluates false because `ev.data` is a string rather than an `ArrayBuffer` which is a direct result of the line below:

https://github.com/rwinright/Unity-WebSockets-Test/blob/4bb54596bad7ce555e67f7c97213efe8ffcca004/Server/WebSocketServer/WebSocketServer/Program.cs#L20

Changing said line to instead send bytes will result in `ev.data` correctly arriving as an `ArrayBuffer` rendering the else branch unneeded. Thus, the jslib could be kept in its original state.

Example:
```cs
string responseMsg = $"Welcome Back! {Get8CharacterRandomString()}";
byte[] responseBytes = System.Text.Encoding.UTF8.GetBytes(responseMsg);
Send(responseBytes);
```

The primary reason this is needed is because, despite [WebSockets supporting more types](https://websockets.spec.whatwg.org/#dom-websocket-send), the [Unity plugin](https://github.com/jirihybek/unity-websocket-webgl) is designed to assume everything is being sent and received as an `ArrayBuffer`.

**Comment by rwinright** [comment]
This is about as close as we can come with newer versions of Unity.
The rest of the API will also have to not use the Runtime variable as well. 
https://github.com/rwinright/Unity-WebSockets-Test/tree/js-lib-revert
